### ISSUE TITLE
error loading 

### ISSUE THREAD

**Issue by Chrisdeparis** [nishant-666/React-weather#1]
Failed to load resource: the server responded with a status of 400 (Bad Request)
The spin Loading still loading on the app...

**Comment by jcardenaslie** [comment]
Yep, the error that shows is 

`
src/App.js
  Line 39:6:  React Hook useEffect has missing dependencies: 'getForecast' and 'getWeather'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
 `

I do not know much of react so I dont know how to solve it hehe, but Im adding a bit of more info to the issue, as I also want to know how to solve it :) 

thanks

**Comment by nishant-666** [comment]
@jcardenaslie Please follow the updated code at https://github.com/nishant-666/React-Weather-alt

Thank you.

**Comment by nishant-666** [comment]
> Failed to load resource: the server responded with a status of 400 (Bad Request)
> The spin Loading still loading on the app...
